os.environ.setdefault("IP", "0.0.0.0")
os.environ.setdefault("PORT", "5000")
os.environ.setdefault("SECRET_KEY", "2HSCs4Fyxg")
os.environ.setdefault("DEBUG", "FALSE")
os.environ.setdefault('DEVELOPMENT', 'True')
os.environ.setdefault("DATABASE_URL", "postgres://wlbzkciu:eRHIhhr3PwostXUeYj0l8JPa6SzvEs68@lucky.db.elephantsql.com/wlbzkciu")
