"""add to recipe model

Revision ID: 1f27c24425f8
Revises: cf56dfeb4dc3
Create Date: 2022-07-15 11:18:29.910995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f27c24425f8'
down_revision = 'cf56dfeb4dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('is_gf', sa.Boolean(), nullable=False))
    op.add_column('recipe', sa.Column('recipe_author', sa.String(length=25), nullable=False))
    op.alter_column('recipe', 'category_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.create_unique_constraint(None, 'recipe', ['recipe_author'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='unique')
    op.alter_column('recipe', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('recipe', 'recipe_author')
    op.drop_column('recipe', 'is_gf')
    # ### end Alembic commands ###
